### PR TITLE
Modified `JavaScriptChart#setData` to run on main thread

### LINKED ISSUE #123: Using Topsoil as a library, setData method of Chart throws JavaFX error
myChart.setData(vc) // where vc is a variable context and myChart is ErrorEllipseChart, line 88 reported below

gives:

Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class javafx.scene.web.WebEngine
	at javafx.scene.web.WebView.<init>(WebView.java:271)
	at org.cirdles.topsoil.chart.JavaScriptChart.initializeWebViewIfNeeded(JavaScriptChart.java:252)
	at org.cirdles.topsoil.chart.JavaScriptChart.setData(JavaScriptChart.java:303)
	at org.earthtime.UPb_Redux.dateInterpretation.TestTopsoil.<init>(TestTopsoil.java:88)

### PR DESCRIPTION
**Pull request by johnzeringue**
Modified `JavaScriptChart#setData` to run on the main thread in order to
fix #123. Basic tests were added.

### CODE REVIEW

**Comment by bowring** [comment]
Does not work.  I have created branch bowring/topsoil-test that has org.earthtime.UPb_Redux.dateInterpretation.TestTopsoil class and a call to its constructor from org.earthtime.ETRedux, line 99.  RUnning ET_Redux loads the main frame and then invokes this constructor call, generating the errors from line 90.  See pom for version of Topsoil.

**Comment by johnzeringue** [comment]
The error on my machine (Java 8u40, OS X):

```
Exception in thread "main" java.lang.NullPointerException: Children: child node is null: parent = VBox@23a5fd2
	at javafx.scene.Parent$2.onProposedChange(Parent.java:432)
	at com.sun.javafx.collections.VetoableListDecorator.addAll(VetoableListDecorator.java:234)
	at com.sun.javafx.collections.VetoableListDecorator.addAll(VetoableListDecorator.java:103)
	at javafx.scene.layout.VBox.<init>(VBox.java:234)
	at org.cirdles.topsoil.chart.JavaFXDisplayable.displayAsJComponent(JavaFXDisplayable.java:42)
	at org.earthtime.UPb_Redux.dateInterpretation.TestTopsoil.<init>(TestTopsoil.java:90)
	at org.earthtime.ETRedux.<init>(ETRedux.java:99)
	at org.earthtime.ETRedux.main(ETRedux.java:145)
Exception in thread "JavaFX Application Thread" netscape.javascript.JSException: ReferenceError: Can't find variable: topsoil
	at com.sun.webkit.dom.JSObject.fwkMakeException(JSObject.java:128)
	at com.sun.webkit.WebPage.twkExecuteScript(Native Method)
	at com.sun.webkit.WebPage.executeScript(WebPage.java:1427)
	at javafx.scene.web.WebEngine.executeScript(WebEngine.java:948)
	at org.cirdles.topsoil.chart.JavaScriptChart.lambda$null$7(JavaScriptChart.java:278)
	at org.cirdles.topsoil.chart.JavaScriptChart$$Lambda$123/1705612765.run(Unknown Source)
	at org.cirdles.topsoil.chart.JavaScriptChart$5.changed(JavaScriptChart.java:230)
	at org.cirdles.topsoil.chart.JavaScriptChart$5.changed(JavaScriptChart.java:221)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.ReadOnlyObjectWrapper$ReadOnlyPropertyImpl.fireValueChangedEvent(ReadOnlyObjectWrapper.java:176)
	at javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:142)
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146)
	at javafx.scene.web.WebEngine$LoadWorker.updateState(WebEngine.java:1226)
	at javafx.scene.web.WebEngine$LoadWorker.dispatchLoadEvent(WebEngine.java:1337)
	at javafx.scene.web.WebEngine$LoadWorker.access$1100(WebEngine.java:1219)
	at javafx.scene.web.WebEngine$PageLoadListener.dispatchLoadEvent(WebEngine.java:1206)
	at com.sun.webkit.WebPage.fireLoadEvent(WebPage.java:2388)
	at com.sun.webkit.WebPage.fwkFireLoadEvent(WebPage.java:2232)
	at com.sun.webkit.Timer.twkFireTimerEvent(Native Method)
	at com.sun.webkit.Timer.fireTimerEvent(Timer.java:83)
	at com.sun.webkit.Timer.notifyTick(Timer.java:64)
	at javafx.scene.web.WebEngine$PulseTimer.lambda$static$45(WebEngine.java:1167)
	at javafx.scene.web.WebEngine$PulseTimer$$Lambda$105/1722546721.pulse(Unknown Source)
	at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Toolkit.java:314)
	at com.sun.javafx.tk.Toolkit$$Lambda$136/619437394.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:313)
	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:340)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:525)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:505)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$400(QuantumToolkit.java:334)
	at com.sun.javafx.tk.quantum.QuantumToolkit$$Lambda$74/2048931170.run(Unknown Source)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
```

**Comment by johnzeringue** [comment]
It seems like I've introduced a race condition with `Platform.runLater` (obvious in retrospect). I'll keep working on a fix.

**Comment by johnzeringue** [comment]
The new version doesn't throw any runtime errors, but it also doesn't show anything in the dialog in your test.

**Comment by bowring** [comment]
OK, thanks ... on the road but will try to give it a spin.

On Thu, May 21, 2015 at 10:49 AM, John Zeringue <notifications@github.com>
wrote:

> The new version doesn't throw any runtime errors, but it also doesn't show
> anything in the dialog in your test.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CIRDLES/Topsoil/pull/142#issuecomment-104306127>.
>



-- 
Jim Bowring
C. Richard Crosby Distinguished Teaching Co-Chair
Principal Investigator, www.CIRDLES.org <http://www.CIRDLES.org%20>

Computer Science
College of Charleston
66 George Street
Charleston, SC 29424

Google Voice: 843.608.1399 (preferred)
Google Email: bowring@gmail.com

Office:
Harbor Walk East (360 Concord Street) Room 308
843.953.0805
http://stono.cs.cofc.edu/~bowring/
bowringj@cofc.edu

R. Buckminster Fuller (1972):
If humanity is to survive aboard our planet, it must become universally
literate and preoccupied with inherently cooperative Comprehensive
Anticipatory Design Science in which every human is concerned with
accomplishing the comfortably sustainable well-faring of all other humans.

**Comment by bowring** [comment]
I can get commit 6534897 from jitpack, but not this commit : 1d14b3b (from
fix-topsoil-library branch)

thoughts?


On Fri, May 22, 2015 at 6:37 AM, Jim Bowring <bowring@gmail.com> wrote:

> OK, thanks ... on the road but will try to give it a spin.
>
> On Thu, May 21, 2015 at 10:49 AM, John Zeringue <notifications@github.com>
> wrote:
>
>> The new version doesn't throw any runtime errors, but it also doesn't
>> show anything in the dialog in your test.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/CIRDLES/Topsoil/pull/142#issuecomment-104306127>.
>>
>
>
>
> --
> Jim Bowring
> C. Richard Crosby Distinguished Teaching Co-Chair
> Principal Investigator, www.CIRDLES.org <http://www.CIRDLES.org%20>
>
> Computer Science
> College of Charleston
> 66 George Street
> Charleston, SC 29424
>
> Google Voice: 843.608.1399 (preferred)
> Google Email: bowring@gmail.com
>
> Office:
> Harbor Walk East (360 Concord Street) Room 308
> 843.953.0805
> http://stono.cs.cofc.edu/~bowring/
> bowringj@cofc.edu
>
> R. Buckminster Fuller (1972):
> If humanity is to survive aboard our planet, it must become universally
> literate and preoccupied with inherently cooperative Comprehensive
> Anticipatory Design Science in which every human is concerned with
> accomplishing the comfortably sustainable well-faring of all other humans.
>



-- 
Jim Bowring
C. Richard Crosby Distinguished Teaching Co-Chair
Principal Investigator, www.CIRDLES.org <http://www.CIRDLES.org%20>

Computer Science
College of Charleston
66 George Street
Charleston, SC 29424

Google Voice: 843.608.1399 (preferred)
Google Email: bowring@gmail.com

Office:
Harbor Walk East (360 Concord Street) Room 308
843.953.0805
http://stono.cs.cofc.edu/~bowring/
bowringj@cofc.edu

R. Buckminster Fuller (1972):
If humanity is to survive aboard our planet, it must become universally
literate and preoccupied with inherently cooperative Comprehensive
Anticipatory Design Science in which every human is concerned with
accomplishing the comfortably sustainable well-faring of all other humans.

**Comment by bowring** [comment]
actually, can't get either of these it turns out, but still can get 8c188fd

**Comment by johnzeringue** [comment]
Try `1909627`.

**Comment by johnzeringue** [comment]
Actually, use `5147a7c`. It's the latest and should work now. The JitPack folks have been helping me out.

**Comment by bowring** [comment]
10.4 thanks

On Fri, May 22, 2015 at 12:06 PM, John Zeringue <notifications@github.com>
wrote:

> Actually, use 5147a7c. It's the latest and should work now. The JitPack
> folks have been helping me out.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CIRDLES/Topsoil/pull/142#issuecomment-104699703>.
>



-- 
Jim Bowring
C. Richard Crosby Distinguished Teaching Co-Chair
Principal Investigator, www.CIRDLES.org <http://www.CIRDLES.org%20>

Computer Science
College of Charleston
66 George Street
Charleston, SC 29424

Google Voice: 843.608.1399 (preferred)
Google Email: bowring@gmail.com

Office:
Harbor Walk East (360 Concord Street) Room 308
843.953.0805
http://stono.cs.cofc.edu/~bowring/
bowringj@cofc.edu

R. Buckminster Fuller (1972):
If humanity is to survive aboard our planet, it must become universally
literate and preoccupied with inherently cooperative Comprehensive
Anticipatory Design Science in which every human is concerned with
accomplishing the comfortably sustainable well-faring of all other humans.

**Comment by bowring** [comment]
Since nothing would display, I made the
call: ((JavaScriptChart)myChart).toSVG();

This produces java.lang.NullPointerException:
at org.cirdles.topsoil.chart.JavaScriptChart.toSVG(JavaScriptChart.java:333)

which means something is awry here (line 331):
Element svgElement = webEngine.getDocument().getElementById("chart");

since svgElement is coming up null

thoughts?

**Comment by bowring** [comment]
During experimental runs, my topsoil test actually plotted ellipses and axis with interactivity...just cannot replicate, so definitely related to threading somehow.  A call to Topsoil.main(null) works great, btw.

**Comment by johnzeringue** [comment]
Current version works on my machine. The last issue was hiding in `JavaFXDisplayable#displayAsJComponent`. It was threading, like you said, although I don't understand how it could've exhibited the behavior you described (working sometimes).

Note that your `TopsoilTest` code has a slight problem with variable ordering. It can be fixed by using the following:

```java
dataEntry.set((Field<? super Double>) myFields.get(0), DATA[i][0]);
dataEntry.set((Field<? super Double>) myFields.get(1), DATA[i][2]);
dataEntry.set((Field<? super Double>) myFields.get(2), DATA[i][1]);
dataEntry.set((Field<? super Double>) myFields.get(3), DATA[i][3]);
dataEntry.set((Field<? super Double>) myFields.get(4), DATA[i][4]);
```

Please verify that the latest commit, `9454b8b`, works on your machine, and I'll merge after I finish cleaning up.

**Comment by bowring** [comment]
Excellent - works great.  Actually I had only seen one instance of ellipses displaying and it was after I was playing with FX functionality.  Good job - now to explore the interface.

**Pull request merged**
