### PR TITLE
Added additional CheckStyle constraints

### PR DESCRIPTION
**Pull request by johnzeringue**
Barred developers from submitting code with trailing whitespace or
consecutive blank lines.

Also forebode `System.out.println()` and its varients in favor of using
proper logging tools.

### CODE REVIEW

**Comment by bowring** [comment]
Not sure barring println() is a good idea.  I, and other developers, often
use println() to monitor runtime processes in the terminal during
development.  We don't want to drive people away. Thoughts?

On Mon, Jun 1, 2015 at 10:57 PM, John Zeringue <notifications@github.com>
wrote:

> Merged #171 <https://github.com/CIRDLES/Topsoil/pull/171>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CIRDLES/Topsoil/pull/171#event-319572600>.
>



-- 
Jim Bowring
C. Richard Crosby Distinguished Teaching Co-Chair
Principal Investigator, www.CIRDLES.org, www.github.com/cirdles

Computer Science
College of Charleston
66 George Street
Charleston, SC 29424

Google Voice: 843.608.1399 (preferred)
Google Email: bowring@gmail.com

Office:
Harbor Walk East (360 Concord Street) Room 308
843.953.0805
http://stono.cs.cofc.edu/~bowring/
bowringj@cofc.edu

R. Buckminster Fuller (1972):
If humanity is to survive aboard our planet, it must become universally
literate and preoccupied with inherently cooperative Comprehensive
Anticipatory Design Science in which every human is concerned with
accomplishing the comfortably sustainable well-faring of all other humans.

**Comment by bowring** [comment]
Consider the scenario for example where a developer does a pull request to
get some advice and includes println() so others can monitor the terminal
to understand the issue.

On Tue, Jun 2, 2015 at 5:32 AM, Jim Bowring <bowring@gmail.com> wrote:

> Not sure barring println() is a good idea.  I, and other developers, often
> use println() to monitor runtime processes in the terminal during
> development.  We don't want to drive people away. Thoughts?
>
> On Mon, Jun 1, 2015 at 10:57 PM, John Zeringue <notifications@github.com>
> wrote:
>
>> Merged #171 <https://github.com/CIRDLES/Topsoil/pull/171>.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/CIRDLES/Topsoil/pull/171#event-319572600>.
>>
>
>
>
> --
> Jim Bowring
> C. Richard Crosby Distinguished Teaching Co-Chair
> Principal Investigator, www.CIRDLES.org, www.github.com/cirdles
>
> Computer Science
> College of Charleston
> 66 George Street
> Charleston, SC 29424
>
> Google Voice: 843.608.1399 (preferred)
> Google Email: bowring@gmail.com
>
> Office:
> Harbor Walk East (360 Concord Street) Room 308
> 843.953.0805
> http://stono.cs.cofc.edu/~bowring/
> bowringj@cofc.edu
>
> R. Buckminster Fuller (1972):
> If humanity is to survive aboard our planet, it must become universally
> literate and preoccupied with inherently cooperative Comprehensive
> Anticipatory Design Science in which every human is concerned with
> accomplishing the comfortably sustainable well-faring of all other humans.
>



-- 
Jim Bowring
C. Richard Crosby Distinguished Teaching Co-Chair
Principal Investigator, www.CIRDLES.org, www.github.com/cirdles

Computer Science
College of Charleston
66 George Street
Charleston, SC 29424

Google Voice: 843.608.1399 (preferred)
Google Email: bowring@gmail.com

Office:
Harbor Walk East (360 Concord Street) Room 308
843.953.0805
http://stono.cs.cofc.edu/~bowring/
bowringj@cofc.edu

R. Buckminster Fuller (1972):
If humanity is to survive aboard our planet, it must become universally
literate and preoccupied with inherently cooperative Comprehensive
Anticipatory Design Science in which every human is concerned with
accomplishing the comfortably sustainable well-faring of all other humans.

**Comment by johnzeringue** [comment]
I considered all of that. My arguments in favor of the move were as follows:

- `System.out.println(someString);` maps one-to-one with `LOGGER.log(INFO, someString);`.
- This rule reminds developers like you (and me!) to remove their debugging code.
- Since half of the project is a library component, we _really_ don't want standard I/O in production.
- There are half a dozen other rules that are _at least_ as tricky as this one.
- `gradle test` will still pass without CheckStyle compliance.
- CheckStyle wouldn't be valuable if we never expected our rules to be violated.

Another argument against is that this rule makes `checkstyle.xml` harder to use CIRDLES-wide due to Redux.

For the moment, I think I'll improve upon the current rule by adding a suggestion to use `Logger` to its message. If we have more concrete issues in the future, I'll rethink this policy.

**Comment by bowring** [comment]
10.4

**Pull request merged**
