### PR TITLE
Fixed bug when spaces in Topsoil path

### LINKED ISSUE #130: String.format breaks when html contains %20 in path to resource
In JavaScriptChart.java, the generation of HTML_TEMPLATE uses URLs made from the full local path.  If these paths have spaces in them, they write as "%20".  String.format throws an error when this is encountered.  I renamed my directories without spaces and all worked well.  Suggestion - maybe we should use relative paths, since inside Topsoil's directories we control naming.   Note this is related to issue #122 but not the full story there.

### PR DESCRIPTION
**Pull request by johnzeringue**
Fixed #130 by refactoring the code to use the new resource extractor
from Commons.

This should address the last stability/portability issue preventing
Topsoil from being used inside of ET_Redux.

### CODE REVIEW

**Comment by johnzeringue** [comment]
@bowring, please test this with ET_Redux before I merge. I've already done that to my satisfaction on my machine, but let's make sure we fix this one for good.

If you can't get to it until next week, that's no problem at all. I understand you have a busy weekend. :wink:

**Comment by johnzeringue** [comment]
Note that the artifact for Topsoil has changed a bit. You can now include it through Maven as follows:

``` xml
<dependency>
    <groupId>com.johnzeringue.topsoil</groupId>
    <artifactId>app</artifactId>
    <version>22d8fc7</version>
</dependency>
```

**Comment by bowring** [comment]
Just getting caught up ... did not get a chance to include with ET_Redux
yet.  What is the rationale for moving artifact out of Cirdles domain?

On Sat, Sep 19, 2015 at 3:38 PM, John Zeringue <notifications@github.com>
wrote:

> Note that the artifact for Topsoil has changed a bit. You can now include
> it through Maven as follows:
>
> <dependency>
>     <groupId>com.johnzeringue.topsoil</groupId>
>     <artifactId>app</artifactId>
>     <version>22d8fc7</version>
> </dependency>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CIRDLES/Topsoil/pull/189#issuecomment-141701014>.
>



-- 
Jim Bowring
C. Richard Crosby Distinguished Teaching Co-Chair
Principal Investigator, www.CIRDLES.org, www.github.com/cirdles

Computer Science
College of Charleston
66 George Street
Charleston, SC 29424

Google Voice: 843.608.1399 (preferred)
Google Email: bowring@gmail.com

Office:
Harbor Walk East (360 Concord Street) Room 308
843.953.0805
http://stono.cs.cofc.edu/~bowring/
bowringj@cofc.edu

R. Buckminster Fuller (1972):
If humanity is to survive aboard our planet, it must become universally
literate and preoccupied with inherently cooperative Comprehensive
Anticipatory Design Science in which every human is concerned with
accomplishing the comfortably sustainable well-faring of all other humans.

**Comment by johnzeringue** [comment]
It isn't being moved out of the CIRDLES domain. It'll be moved *into* the CIRDLES domain if you merge this pull request.

**Comment by bowring** [comment]
cool ... will get on it tonight

On Mon, Sep 28, 2015 at 12:10 PM, John Zeringue <notifications@github.com>
wrote:

> It isn't being moved out of the CIRDLES domain. It'll be moved *into* the
> CIRDLES domain if you merge this pull request.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CIRDLES/Topsoil/pull/189#issuecomment-143791721>.
>



-- 
Jim Bowring
C. Richard Crosby Distinguished Teaching Co-Chair
Principal Investigator, www.CIRDLES.org, www.github.com/cirdles

Computer Science
College of Charleston
66 George Street
Charleston, SC 29424

Google Voice: 843.608.1399 (preferred)
Google Email: bowring@gmail.com

Office:
Harbor Walk East (360 Concord Street) Room 308
843.953.0805
http://stono.cs.cofc.edu/~bowring/
bowringj@cofc.edu

R. Buckminster Fuller (1972):
If humanity is to survive aboard our planet, it must become universally
literate and preoccupied with inherently cooperative Comprehensive
Anticipatory Design Science in which every human is concerned with
accomplishing the comfortably sustainable well-faring of all other humans.

**Pull request merged**
