### PR TITLE
Second try at enhancement

### PR DESCRIPTION
**Pull request by wyattwmorris**

### CODE REVIEW

**Comment by johnzeringue** [comment]
Do you think the variables make your code more readable?

**Comment by wyattwmorris** [comment]
I would not be opposed to changing them at all. I would agree there is room for improvement there. Did you have anything in mind?

**Comment by johnzeringue** [comment]
I was curious what you thought of getting rid of them and just using literals.

**Comment by johnzeringue** [comment]
This works on my machine. However, it's still not idiomatic Bash. Consider this sample program:

    SUBFOLDER=Documents
    ls ~/$SUBFOLDER/Topsoil

I think there are a few simplifications you can glean from this and then we'll merge this.

Good work so far, though!

**Pull request closed without merging**
