### PR TITLE
McLean Regression slope rounds to 5 sigfigs

### PR DESCRIPTION
**Pull request by GarreBrenn**
CAUTION: I don't know if Regression.getSlope() is used anywhere for _actual calculations_, I am working under the assumption that it's only called in order to _display_ the regression slope above the plot. We don't want a rounded value used for calculations.

### CODE REVIEW

**Comment by bowring** [comment]
good start, but
1) we don't want to change getslope, rather we want to format the result of getslope
2) we can't change topsoil.js directly here, we need to make a pull request to the topsoil.js repository for a change to topsoil.ts - I will show you how in our online meeting.

**Comment by bowring** [comment]
getting there-
let's add a int parameter 'sigDigits' to this signature to make it more robust, so we are not wedded to "5":
public double getRoundedSlope() >> public double getRoundedSlope(int sigDigits)

**Comment by GarreBrenn** [comment]
Should be good to go now!

**Comment by bowring** [comment]
@GarreBrenn - add your intercept rounding method here too

**Pull request merged**
