### PR TITLE
Added evolution chart

### PR DESCRIPTION
**Pull request by johnzeringue**

### CODE REVIEW

**Comment by johnzeringue** [comment]
What it currently looks like:
screen shot 2015-12-09 at 10 20 22 pm

**Comment by bowring** [comment]
nice

On Wed, Dec 9, 2015 at 10:21 PM, John Zeringue <notifications@github.com>
wrote:

> What it currently looks like:
> [image: screen shot 2015-12-09 at 10 20 22 pm]
> <https://cloud.githubusercontent.com/assets/3858785/11706029/1f7ed6e2-9ec3-11e5-82c1-7d4ced3cb810.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CIRDLES/Topsoil/pull/253#issuecomment-163473094>.
>



-- 
Jim Bowring
C. Richard Crosby Distinguished Teaching Co-Chair
Principal Investigator, www.CIRDLES.org, www.github.com/cirdles

Computer Science
College of Charleston
66 George Street
Charleston, SC 29424

Google Voice: 843.608.1399 (preferred)
Google Email: bowring@gmail.com

Office:
Harbor Walk East (360 Concord Street) Room 308
843.953.0805
http://stono.cs.cofc.edu/~bowring/
bowringj@cofc.edu

R. Buckminster Fuller (1972):
If humanity is to survive aboard our planet, it must become universally
literate and preoccupied with inherently cooperative Comprehensive
Anticipatory Design Science in which every human is concerned with
accomplishing the comfortably sustainable well-faring of all other humans.

**Comment by noahmclean** [comment]
Excellent!!!  This looks great!

**Comment by ryanickert** [comment]
I was actually motivated to say the same thing, but wasn't sure how just
praise at nice design would play here.  (Great design!!)

**Comment by johnzeringue** [comment]
@ryanickert, the design is @noahmclean's. I based this off of a MATLAB script of his.

**Comment by johnzeringue** [comment]
Current version with appropriate data:
screen shot 2015-12-15 at 12 48 19 pm

It's definitely not perfect yet, the two main problems being:
1. The isochrons and contours don't adjust plot bounds.
2. The math seems a little brittle given 64-bit floating points (although this might be fixed by plot bounds adjustments).

However, I'll address these in future updates.

**Comment by bowring** [comment]
yeah!

On Tue, Dec 15, 2015 at 12:57 PM, John Zeringue <notifications@github.com>
wrote:

> Current version with appropriate data:
> [image: screen shot 2015-12-15 at 12 48 19 pm]
> <https://cloud.githubusercontent.com/assets/3858785/11818766/31f25220-a32a-11e5-93da-f3f23da19ade.png>
>
> It's definitely not perfect yet, the two main problems being:
>
>    1. The isochrons and contours don't adjust with plot bounds.
>    2. The math seems a little brittle given 64-bit floating points
>    (although this might be fixed by plot bounds adjustments).
>
> However, I'll address these in future updates.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CIRDLES/Topsoil/pull/253#issuecomment-164840333>.
>



-- 
Jim Bowring
C. Richard Crosby Distinguished Teaching Co-Chair
Principal Investigator, www.CIRDLES.org, www.github.com/cirdles

Computer Science
College of Charleston
66 George Street
Charleston, SC 29424

Google Voice: 843.608.1399 (preferred)
Google Email: bowring@gmail.com

Office:
Harbor Walk East (360 Concord Street) Room 308
843.953.0805
http://stono.cs.cofc.edu/~bowring/
bowringj@cofc.edu

R. Buckminster Fuller (1972):
If humanity is to survive aboard our planet, it must become universally
literate and preoccupied with inherently cooperative Comprehensive
Anticipatory Design Science in which every human is concerned with
accomplishing the comfortably sustainable well-faring of all other humans.

**Pull request merged**
