### PR TITLE
Overhaul

### PR DESCRIPTION
**Pull request by marottajb**
- Addresses #428 and #429 by implementing DataTemplate for alternately structured table files
- Gets rid of SpreadsheetView in light of its exclusion from newer versions of Java, replaces it with a new set of data models.
- Introduces a TreeTableView for viewing data
- Refactors most things to adhere to the new data models
- Splits large classes into smaller pieces

Known issues:
- Table exporting is currently unavailable for Squid 3 data.

### CODE REVIEW

**Comment by bowring** [comment]
@marottajb - should I review this yet? the checks are failing.

**Comment by marottajb** [comment]
@bowring No, I'm still working. I'll let you know and take the in-progress label off.

**Comment by bowring** [comment]
Right out of the box for sample tables, can't load plot:
```
Exception in thread "JavaFX Application Thread" java.lang.RuntimeException: java.io.IOException: Could not load plot-properties-panel.fxml
	at org.cirdles.topsoil.app.control.plot.panel.PlotPropertiesPanel.<init>(PlotPropertiesPanel.java:456)
```

**Comment by marottajb** [comment]
@bowring Plotting is toward the end of my to-do list because I know that Bryce is working on replacing the plotting system. I sent an email with a list of the implemented features.

**Comment by marottajb** [comment]
It appears that in fixing the decimal alignment, I've broken project serialization. Currently working on it, I'll comment when it's fixed.

**Comment by marottajb** [comment]
I pushed the changes fixing the bugs when saving a project.

**Comment by bowring** [comment]
@marottajb -

Looking impressive! 

I am working my way through it and will leave notes here in this comment in no particular order

1) main window needs to open in center of screen and the layout of the logo and about and links should be pleasingly centered; I love the recent files option
2) in constants editor R238_235S is not a Lambda and the default value should be 137.818;  also lets name them Lambda234  etc without the U or Th and include 226,230,231,232,234,235,238 with latest values until we introduce models found [here](https://raw.githubusercontent.com/CIRDLES/Squid/master/squidCore/src/main/resources/org/cirdles/squid/parameters/parameterModels/physicalConstantsModels/EARTHTIME%20Physical%20Constants%20Model%20v.1.1.xml).
3) menu item file/open sample s.b. open example
4) the new project menu item does not behave intuitively - we can discuss
5) what's up with editing cells in data table? - I can't
6) will import support the label column also?
7) table options - crashes the program if I open table options and then move the mouse to this editing pane in github - it does not crash if I move to netbeans - leaves a nice trace of the crash conditions in netbeans output window - may have to demo in person
8) table options - the "assign variables table needs to be larger so the headings are complete and the rows all show at least up to the available real estate
9) the about window version is wrong - also wrong on front page
10) ...

**Comment by bowring** [comment]
I am reviewing - standby.

**Comment by bowring** [comment]
1) still opens low in window on 2 monitor mac ... see how Squid does this
2) still does not save table settings of variable assignments for Squid project
3) the variable assignments window is not sizing correctly and includes doubled up scroll bars
4) pdf errors out on squid file concordia output

**Comment by marottajb** [comment]
@bowring Items 2 and 4 should be fixed, I'm working on item 3, but could you post a picture of item 1?

**Comment by bowring** [comment]
what's up?

**Comment by bowring** [comment]
looking good.

1) MRU list of projects should show full path
2) MRU list should be pre-processed each time to remove missing files (see Squid)
3) screen shot of table editor on MACOS shows scaling issue attached
tableedit

**Comment by bowring** [comment]
I note also that I can open several plots at the same time with no mis-behavior - has something changed or is this a quirk?

**Comment by marottajb** [comment]
I wish I could claim credit for that, but it seems like a happy accident, for the moment. I'm looking into why that's happening and whether it's stable, but should I fix the restriction to one plot for the time being?

**Comment by bowring** [comment]
Looking better.

We need to address the Wetherill / TW issue further - for example when I switch to TW while viewing a Wetherill and try to zoom, Topsoil hangs.  We should implement logic that detects the correct context for each plot - they have different ratios on the axes and more importantly, the axes are constrained:

TW: x: 1.0 to 6500; y: 0.046 to 0.625
W: x: 0.0 to 93.0; y: 0.0 to 2.05

btw, there will also be a bounds check (still to come) for Th and evolution plots

obviously a lot of this will be user beware, but we wan't to at least stop runaway zooming that hangs the app

if the visible axes won't support the W or TW, it should be greyed out - also since both can' appear at the same time, the presentation of the choice should be Concordia : W or TW : one set of colors

we should use these value to stop zoom out also

we should limit the axis extents to 3 decimal places in the axis styling menu

keep up the good work ... when we meet Wed we can produce a more rigorous review

**Comment by cwmagee** [comment]
Tera-Wasserberg plots are actually originally designed (by Tera and Wasserberg) to display common (non-radiogenic) Pb compositions- their adaption to radiogenic Pb is a more recent trend, and they are often used when both types of Pb are mixed.
As a result, the range of plottable values need to include  the range of common Pb isotopic compositions, not just radiogenic ones.

The common Pb composition on  a TW diagram is the y intercept, so you need to be able to display an x-axis value of zero. For young zircons, the X axis value can be very large- but the usefullness of the plot decreases above values of 10,000 or so because intermediate decay products and secular disequilibrium become significant. I think the  largest value I have measured on SHRIMP is about 50,000, but it was garbage data.

For the Y axis, the 207/206 ratio of common Pb from global Pb isotope evolution models reaches a maximum at just under 1.3, so the plot needs to be able to go that high. In theory, young thorium-rich proactinium-poor minerals can go below 0.046, but I have never seen that.

**Comment by noahmclean** [comment]
@cwmagee Head on over to my [`UThPb` repository](https://github.com/noahmclean/UThPb) for all your U-Pb plus disequilbrium plotting and calculation needs.  No ratio too large, no decay chain too long, no date too young!  Example datasets included at no extra cost.

**Comment by ryanickert** [comment]
@cwmagee, Parrish (1990; CJES v27 p1431) published some monazite analyses that are <0.046, as you predict.  :)

**Comment by cwmagee** [comment]
No decay chain too long? So finally I can use Califonium-Curium dating on these zircons:
https://www.sciencedirect.com/science/article/pii/S0149197016301445

**Comment by noahmclean** [comment]
No californium-curium, but the 238U and 235U decay chains have plenty to offer!  I like these visualizations:

http://periodictable.com/Isotopes/092.238/index.full.html
http://periodictable.com/Isotopes/092.235/index.full.html

At present, [UThPb ](https://github.com/noahmclean/UThPb) only handles 238U - 234U - 230Th - 226Ra - 206Pb and 235U - 231Pa - 207Pb, but you could add more isotopes stably with the algorithms I came up with.  It's all about the eigenvectors!

**Pull request merged**
