### PR TITLE
Various Improvements

### PR DESCRIPTION
**Pull request by marottajb**

### CODE REVIEW

**Comment by bowring** [comment]
Just playing with Squid 3 example data - if I choose only one point in the data table, the plot still shows many points

**Comment by bowring** [comment]
provide table option for number of significant digits showing

**Comment by bowring** [comment]
sort order in project structure seems random

**Comment by bowring** [comment]
It appears there is a very sluggish response to choosing a sample checkbox selector - it is veeeery slow to populate the member fractions check boxes - this is the source of the comment above re: choosing one fraction only

**Comment by marottajb** [comment]
@bowring The sluggish response should be fixed now. Working on significant digits and project structure sort order.

**Comment by bowring** [comment]
Much better!

**Comment by bowring** [comment]
At the top of the plot window it says "Scatterplot : null" while I am plotting Squid 3 example data.

**Comment by bowring** [comment]
Snap to corners is only meaningful for concordia - we are snapping the concordia to the corners;  really probably only for wetherill-type

**Comment by bowring** [comment]
note - label sorting should use the intuitive sorter for strings used in Squid3 and ET_Redux so that 123 comes after 1111 . just like abc comes after aaaa

**Comment by bowring** [comment]
Also - I can't reliably reproduce this, but the Mclean regression uncertainty envelope does not always render correctly, sometimes just hugging the regression line from end to end

**Comment by bowring** [comment]
note also, regression should not be available unless there are at least 3 points

**Pull request merged**
